### ISSUE TITLE
Make compatible with Python 3

### ISSUE THREAD

**Issue by jangeador** [birdsarah/django-spreadsheetresponsemixin#16]
Currently when I try to use with python 3 it complains that there isn't a module named StringIO. Looking through Google I read that StringIO.StringIO is now io.StringIO

**Comment by birdsarah** [comment]
thanks for the report, its only testing against py26 and 27 at the moment. i need to fix that.

**Comment by birdsarah** [comment]
Closing issue. This project is deprecated in favor of [django-tables2](https://github.com/jieter/django-tables2) export functionality.
