### ISSUE TITLE
Should we deprecate this in favour of django-tables2 export functionality?

### ISSUE THREAD

**Issue by martinburchell** [birdsarah/django-spreadsheetresponsemixin#17]
@birdsarah We've updated our fork https://github.com/aptivate/django-spreadsheetresponsemixin when moving one of our projects to Django 1.11 and we notice that django-tables2 now has export functionality. Would it make sense to advise people to use django-tables2 instead? django-tables2 has better support for non-database querysets such as Haystack

**Comment by birdsarah** [comment]
That's a very good idea.
